-
  name: app1
  link: www.app2.com
-
  name: app2
  link: www.example.com
-
  name: app3
  link: www.example.com
-
  name: app4
  link: www.example.com
-
  name: app5
  link: www.example.com
-
  name: app6
  link: www.example.com
-
  name: app7
  link: www.example.com
-
  name: app8
  link: www.example.com
-
  name: app9
  link: www.example.com
-
  name: app10
  link: www.example.com
-
  name: app11
  link: www.example.com
